<?php

/*
 *	Implementation of hook_user
 *
 */
function loginlogout_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'logout':
      if (!$_REQUEST['destination']) break;
      global $user ;
      $user_temp = $user;
      $user = user_load(0);
      $item = menu_get_item($_REQUEST['destination']);
      if (!$item['access']) $_REQUEST['destination'] =  '';
    
      $user = $user_temp;
    break;
  }
}

/*
 *	Implementation of hook_init
 *
 */
function loginlogout_init() {
  $path = drupal_get_path('module', 'loginlogout');
  drupal_add_js($path .'/loginlogout.js');
  $settings = array('loginlogout' => array(
    'destination' => drupal_get_destination(),
  ));
  $settings['loginlogout']['urls'] = array(
    url('user/login') => url('user/login', array('query'=>drupal_get_destination())),
    url('logout') =>  url('logout', array('query'=>drupal_get_destination())),
  );
  if (!user_is_logged_in()) { // fixme
     $settings['loginlogout']['urls'][url('user')] = url('user', array('query'=>drupal_get_destination()));
  }
  foreach(variable_get('loginlogout_additional_urls',array()) as $path) {
     $url = url($path);
     if ($url) $settings['loginlogout']['urls'][$url] = url($path, array('query'=>drupal_get_destination()));
  }
  drupal_add_js($settings ,'setting');
}
